services:
  devcontainer:
    build: .
  environment:
    - CONSUL_HTTP_ADDR=http://consul:8500

  redis:
    image: redis:latest

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0